<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Meal;
use App\Models\MealImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MealSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (Category::count() === 0) {
            $this->call(CategorySeeder::class);
        }

        $categoryMap = Category::query()->pluck('id', 'name');

        $meals = [
            [
                'category' => 'Burgers & Sandwiches',
                'name' => 'Classic Beef Burger',
                'description' => 'Juicy grilled beef patty with cheddar, lettuce, tomato, onion, and signature house sauce on a toasted brioche bun.',
                'price' => 540.00,
                'discount_price' => 470.00,
                'stock_quantity' => 45,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 18,
                'avg_rating' => 4.7,
                'review_count' => 182,
            ],
            [
                'category' => 'Burgers & Sandwiches',
                'name' => 'Chicken Crispy Burger',
                'description' => 'Crispy fried chicken breast with spicy mayo, pickles, lettuce, and melted cheese for a crunchy bite.',
                'price' => 490.00,
                'discount_price' => 420.00,
                'stock_quantity' => 38,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 16,
                'avg_rating' => 4.6,
                'review_count' => 146,
            ],
            [
                'category' => 'Burgers & Sandwiches',
                'name' => 'Smoky BBQ Sandwich',
                'description' => 'Slow-cooked pulled chicken with barbecue glaze, caramelized onions, and creamy slaw in a toasted bun.',
                'price' => 520.00,
                'discount_price' => null,
                'stock_quantity' => 30,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 20,
                'avg_rating' => 4.4,
                'review_count' => 91,
            ],
            [
                'category' => 'Pizza & Pasta',
                'name' => 'Margherita Supreme Pizza',
                'description' => 'Wood-fired pizza with mozzarella, basil, tomato sauce, and a touch of extra virgin olive oil.',
                'price' => 680.00,
                'discount_price' => 610.00,
                'stock_quantity' => 26,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 22,
                'avg_rating' => 4.8,
                'review_count' => 220,
            ],
            [
                'category' => 'Pizza & Pasta',
                'name' => 'Pepperoni Feast Pizza',
                'description' => 'Loaded with pepperoni, mozzarella, roasted peppers, and a rich tomato base on a thin crust.',
                'price' => 760.00,
                'discount_price' => null,
                'stock_quantity' => 22,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 25,
                'avg_rating' => 4.5,
                'review_count' => 174,
            ],
            [
                'category' => 'Pizza & Pasta',
                'name' => 'Creamy Chicken Alfredo',
                'description' => 'Fettuccine in a parmesan cream sauce with grilled chicken, mushrooms, and garlic.',
                'price' => 650.00,
                'discount_price' => 570.00,
                'stock_quantity' => 32,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 17,
                'avg_rating' => 4.7,
                'review_count' => 163,
            ],
            [
                'category' => 'Grilled Chicken',
                'name' => 'Lemon Herb Chicken Plate',
                'description' => 'Grilled chicken breast served with roasted potatoes, seasonal vegetables, and a lemon herb drizzle.',
                'price' => 620.00,
                'discount_price' => null,
                'stock_quantity' => 35,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 19,
                'avg_rating' => 4.6,
                'review_count' => 138,
            ],
            [
                'category' => 'Grilled Chicken',
                'name' => 'Peri Peri Chicken Wrap',
                'description' => 'Char-grilled chicken strips with peri peri sauce, lettuce, crispy onions, and garlic mayo in a soft tortilla.',
                'price' => 460.00,
                'discount_price' => 390.00,
                'stock_quantity' => 41,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 15,
                'avg_rating' => 4.5,
                'review_count' => 112,
            ],
            [
                'category' => 'Healthy Bowls',
                'name' => 'Falafel Power Bowl',
                'description' => 'Crispy falafel, quinoa, hummus, cucumber, tomatoes, parsley, and tahini dressing.',
                'price' => 500.00,
                'discount_price' => null,
                'stock_quantity' => 28,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 14,
                'avg_rating' => 4.8,
                'review_count' => 201,
            ],
            [
                'category' => 'Healthy Bowls',
                'name' => 'Salmon Protein Bowl',
                'description' => 'Seared salmon, brown rice, avocado, edamame, greens, and sesame soy dressing.',
                'price' => 820.00,
                'discount_price' => 730.00,
                'stock_quantity' => 18,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 21,
                'avg_rating' => 4.9,
                'review_count' => 188,
            ],
            [
                'category' => 'Healthy Bowls',
                'name' => 'Chickpea & Greens Bowl',
                'description' => 'Roasted chickpeas, kale, sweet potato, pomegranate, and lemon vinaigrette for a fresh vibrant meal.',
                'price' => 490.00,
                'discount_price' => null,
                'stock_quantity' => 34,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 13,
                'avg_rating' => 4.4,
                'review_count' => 94,
            ],
            [
                'category' => 'Seafood',
                'name' => 'Garlic Butter Shrimp',
                'description' => 'Succulent shrimp sautéed in garlic butter, herbs, and lemon served with rice and grilled vegetables.',
                'price' => 740.00,
                'discount_price' => 660.00,
                'stock_quantity' => 25,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 18,
                'avg_rating' => 4.7,
                'review_count' => 142,
            ],
            [
                'category' => 'Seafood',
                'name' => 'Citrus Salmon Fillet',
                'description' => 'Pan-seared salmon with orange glaze, asparagus, and herb potatoes for a light gourmet finish.',
                'price' => 860.00,
                'discount_price' => null,
                'stock_quantity' => 20,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 24,
                'avg_rating' => 4.8,
                'review_count' => 129,
            ],
            [
                'category' => 'Seafood',
                'name' => 'Seafood Linguine',
                'description' => 'A rich seafood pasta with mussels, calamari, shrimp, garlic, white wine, and parsley.',
                'price' => 930.00,
                'discount_price' => 820.00,
                'stock_quantity' => 19,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 26,
                'avg_rating' => 4.9,
                'review_count' => 173,
            ],
            [
                'category' => 'Wraps & Rolls',
                'name' => 'Chicken Caesar Wrap',
                'description' => 'Grilled chicken, romaine, parmesan, Caesar dressing, and crunchy croutons wrapped in a soft flatbread.',
                'price' => 430.00,
                'discount_price' => null,
                'stock_quantity' => 44,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 12,
                'avg_rating' => 4.3,
                'review_count' => 105,
            ],
            [
                'category' => 'Wraps & Rolls',
                'name' => 'Beef Tacos Deluxe',
                'description' => 'Tender beef, black beans, pico de gallo, lettuce, and cheddar in warm tortillas with lime crema.',
                'price' => 470.00,
                'discount_price' => 420.00,
                'stock_quantity' => 31,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 16,
                'avg_rating' => 4.6,
                'review_count' => 124,
            ],
            [
                'category' => 'Breakfast',
                'name' => 'Avocado Egg Toast',
                'description' => 'Sourdough toast topped with smashed avocado, poached eggs, chili flakes, and feta.',
                'price' => 360.00,
                'discount_price' => null,
                'stock_quantity' => 48,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 10,
                'avg_rating' => 4.7,
                'review_count' => 136,
            ],
            [
                'category' => 'Breakfast',
                'name' => 'Classic Full English Breakfast',
                'description' => 'Eggs, grilled tomatoes, mushrooms, beans, toast, and your choice of bacon or turkey sausage.',
                'price' => 610.00,
                'discount_price' => 530.00,
                'stock_quantity' => 25,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 22,
                'avg_rating' => 4.5,
                'review_count' => 88,
            ],
            [
                'category' => 'Desserts',
                'name' => 'Chocolate Lava Cake',
                'description' => 'Warm dark chocolate cake with a molten center, vanilla bean cream, and fresh berries.',
                'price' => 280.00,
                'discount_price' => null,
                'stock_quantity' => 60,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 9,
                'avg_rating' => 4.9,
                'review_count' => 255,
            ],
            [
                'category' => 'Desserts',
                'name' => 'Classic Cheesecake',
                'description' => 'Creamy New York cheesecake with a buttery biscuit base and berry compote.',
                'price' => 260.00,
                'discount_price' => 220.00,
                'stock_quantity' => 54,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 8,
                'avg_rating' => 4.6,
                'review_count' => 119,
            ],
            [
                'category' => 'Drinks',
                'name' => 'Fresh Berry Smoothie',
                'description' => 'A tropical blend of strawberry, blueberry, banana, yogurt, and almond milk.',
                'price' => 210.00,
                'discount_price' => null,
                'stock_quantity' => 72,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 6,
                'avg_rating' => 4.7,
                'review_count' => 132,
            ],
            [
                'category' => 'Drinks',
                'name' => 'Iced Latte',
                'description' => 'Espresso with chilled milk and a creamy finish, served over ice with optional vanilla.',
                'price' => 180.00,
                'discount_price' => 150.00,
                'stock_quantity' => 90,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 5,
                'avg_rating' => 4.4,
                'review_count' => 98,
            ],
            [
                'category' => 'Vegan & Vegetarian',
                'name' => 'Roasted Veggie Pasta',
                'description' => 'Pasta tossed with roasted zucchini, peppers, eggplant, garlic, olives, and basil pesto.',
                'price' => 620.00,
                'discount_price' => null,
                'stock_quantity' => 29,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 17,
                'avg_rating' => 4.7,
                'review_count' => 127,
            ],
            [
                'category' => 'Vegan & Vegetarian',
                'name' => 'Garden Falafel Plate',
                'description' => 'Crispy falafel served with a fresh salad, hummus, tahini, and warm pita bread.',
                'price' => 510.00,
                'discount_price' => 430.00,
                'stock_quantity' => 33,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 15,
                'avg_rating' => 4.5,
                'review_count' => 115,
            ],
            [
                'category' => 'Family Meals',
                'name' => 'Family Grill Combo',
                'description' => 'A generous sharing platter with grilled chicken, fries, rice, salad, and dipping sauces.',
                'price' => 1180.00,
                'discount_price' => 1040.00,
                'stock_quantity' => 14,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 28,
                'avg_rating' => 4.8,
                'review_count' => 167,
            ],
            [
                'category' => 'Family Meals',
                'name' => 'Mega Pasta Feast',
                'description' => 'A family-size pasta tray featuring bolognese, garlic bread, parmesan, and side salad.',
                'price' => 1070.00,
                'discount_price' => null,
                'stock_quantity' => 12,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 26,
                'avg_rating' => 4.4,
                'review_count' => 93,
            ],
            [
                'category' => 'Appetizers',
                'name' => 'Loaded Fries Basket',
                'description' => 'Golden fries topped with cheese sauce, jalapenos, herbs, and crispy onions.',
                'price' => 340.00,
                'discount_price' => 290.00,
                'stock_quantity' => 58,
                'is_available' => true,
                'is_featured' => true,
                'preparation_time' => 10,
                'avg_rating' => 4.6,
                'review_count' => 140,
            ],
            [
                'category' => 'Appetizers',
                'name' => 'Crispy Mozzarella Sticks',
                'description' => 'Golden fried mozzarella with marinara dip and basil seasoning.',
                'price' => 300.00,
                'discount_price' => null,
                'stock_quantity' => 62,
                'is_available' => true,
                'is_featured' => false,
                'preparation_time' => 9,
                'avg_rating' => 4.5,
                'review_count' => 108,
            ],
        ];

        foreach ($meals as $mealData) {
            $categoryId = $categoryMap->get($mealData['category']);

            if (! $categoryId) {
                continue;
            }

            $meal = Meal::updateOrCreate(
                ['slug' => Str::slug($mealData['name'])],
                [
                    'category_id' => $categoryId,
                    'name' => $mealData['name'],
                    'description' => $mealData['description'],
                    'price' => $mealData['price'],
                    'discount_price' => $mealData['discount_price'],
                    'stock_quantity' => $mealData['stock_quantity'],
                    'is_available' => $mealData['is_available'],
                    'is_featured' => $mealData['is_featured'],
                    'preparation_time' => $mealData['preparation_time'],
                    'avg_rating' => $mealData['avg_rating'],
                    'review_count' => $mealData['review_count'],
                ]
            );

            $meal->images()->delete();

            foreach ([0, 1] as $index) {
                MealImage::factory()->create([
                    'meal_id' => $meal->id,
                    'sort_order' => $index,
                    'is_primary' => $index === 0,
                ]);
            }
        }
    }
}
